version: "3.8"

services:
  bridge:
    build:
      context: ../..
      dockerfile: ./packages/bridge/Dockerfile

  composer:
    build:
      context: ../..
      dockerfile: ./packages/composer/Dockerfile
